version: '3.3'
services:
  db:
    restart: on-failure
    container_name: danangqueen_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=danaqueen
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data